FROM golang:1.22

RUN mkdir goproject
WORKDIR /goproject

RUN git clone https://github.com/naufalseira/Assignment-2-NSP.git

WORKDIR /goproject/Assignment-2-NSP/app

ENV PORT=8080

RUN go run server.go